[package]
name = "gvltctl"
version = "0.1.0"
edition = "2021"
authors = ["Gevulot Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/gevulotnetwork/gvltctl"
description = "Gevulot Control CLI"

[dependencies]
# TODO: change rev to tag when available
gevulot-rs = { git = "https://github.com/gevulotnetwork/gevulot-rs.git", rev = "6695dcb0e7214a3ec07cdc2d83bbc4ff26ae2d38" }

bip32 = "0.5.1"
clap = { version = "4", features = ["env", "cargo"] }
clap_complete = "4.5.13"
cosmrs = "0.20"
env_logger = "0.11.5"
rand_core = "0.6.4"
serde = "1"
serde_json = "1"
serde_yaml = "0.9.34"
tokio = { version = "1", features = ["full"] }
toml = "0.8.19"

[target.'cfg(target_os = "linux")'.dependencies]
mia-rt-config = { git = "https://github.com/gevulotnetwork/mia.git", tag = "v0.2.1" }
mia-installer = { git = "https://github.com/gevulotnetwork/mia.git", tag = "v0.2.1" }

anyhow = "1"
log = "0.4.22"
num_cpus = "1.16.0"
oci-spec = "0.7.0"
tempdir = "0.3.7"
thiserror = "1"
