FROM ubuntu:24.04 as builder

RUN apt-get update

WORKDIR /gvltctl

# Install build dependencies
# Rust
RUN apt-get install -y curl
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="$PATH:/root/.cargo/bin"

# Buf
RUN curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.47.2/buf-Linux-x86_64" -o /usr/local/bin/buf
RUN chmod +x /usr/local/bin/buf
RUN apt-get remove -y --auto-remove curl

# deb packages
RUN apt-get install -y \
    build-essential \
    pkg-config \
    protobuf-compiler \
    libssl-dev

# Copy sources
COPY src/ src/
COPY build.rs build.rs
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# Build sources
RUN cargo build --features vm-builder-v2

FROM ubuntu:24.04

# Install runtime dependencies for gvltctl
RUN apt-get update
RUN apt-get install -y \
    ca-certificates \
    # Working with containers
    podman \
    # Linux kernel build dependencies (not needed if using pre-compiled kernel)
    git build-essential libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm bc \
    # Working with VM filesystem
    fuse2fs e2fsprogs

# To allow podman pulling docker images
RUN echo "unqualified-search-registries = [\"docker.io\"]" >> /etc/containers/registries.conf

COPY --from=builder /gvltctl/target/debug/gvltctl /usr/bin/gvltctl

ENTRYPOINT ["gvltctl"]
